# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0710d0ad03ff0d6c235a37d16acc5e143c5609179485181cba1fa12064ef0d9008ad7c70677a9983095236918b731a1847dd976cdce57b73bdaaea6cbef8c0b3

test:
  secret_key_base: 4f2abaa38cd5611b2d1a10d5350ee14aeb2f103c0c1acadb7558ab3bc1e1c5df01a5a1cf6ffe6598b92bc101291cf8feee18a43715d78cdd695bf73df2ab1005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
